source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.4.0'
pod 'SwiftyJSON', '~> 2.3.1'

pod 'SnapKit', '~> 0.21.0’
pod 'MJRefresh', '~> 3.1.2’
pod 'MBProgressHUD', '~> 0.9.2'

pod 'Kingfisher', '~> 2.4.1'

pod 'ALCameraViewController', '~> 1.1.9'

pod 'WebViewJavascriptBridge', '~> 5.0.5'
